version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 5555:80
    environment:
      WORDPRESS_DB_PASSWORD: example
    volumes:
      - .:/var/www/html/wp-content/themes/cl
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin:latest
  #   ports:
  #     - "4445:80"
  #   depends_on:
  #     - mysql